package com.clingsync.android.ui.theme

import androidx.compose.ui.graphics.Color

// Material 3 Light Theme Colors
val md_theme_light_primary = Color(0xFF8E4957)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD9DE)
val md_theme_light_onPrimaryContainer = Color(0xFF71333F)
val md_theme_light_secondary = Color(0xFF75565B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD9DE)
val md_theme_light_onSecondaryContainer = Color(0xFF5C3F43)
val md_theme_light_tertiary = Color(0xFF795831)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDDBA)
val md_theme_light_onTertiaryContainer = Color(0xFF5F411C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF93000A)
val md_theme_light_background = Color(0xFFFFF8F7)
val md_theme_light_onBackground = Color(0xFF22191A)
val md_theme_light_surface = Color(0xFFFFF8F7)
val md_theme_light_onSurface = Color(0xFF22191A)
val md_theme_light_surfaceVariant = Color(0xFFF3DDDF)
val md_theme_light_onSurfaceVariant = Color(0xFF524345)
val md_theme_light_outline = Color(0xFF847375)
val md_theme_light_outlineVariant = Color(0xFFD6C2C3)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF382E2F)
val md_theme_light_inverseOnSurface = Color(0xFFFEEDEE)
val md_theme_light_inversePrimary = Color(0xFFFFB2BE)
val md_theme_light_surfaceDim = Color(0xFFE7D6D7)
val md_theme_light_surfaceBright = Color(0xFFFFF8F7)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFFFF0F1)
val md_theme_light_surfaceContainer = Color(0xFFFBEAEB)
val md_theme_light_surfaceContainerHigh = Color(0xFFF5E4E5)
val md_theme_light_surfaceContainerHighest = Color(0xFFF0DEE0)

// Material 3 Dark Theme Colors
val md_theme_dark_primary = Color(0xFFFFB2BE)
val md_theme_dark_onPrimary = Color(0xFF561D2A)
val md_theme_dark_primaryContainer = Color(0xFF71333F)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD9DE)
val md_theme_dark_secondary = Color(0xFFE5BDC2)
val md_theme_dark_onSecondary = Color(0xFF43292D)
val md_theme_dark_secondaryContainer = Color(0xFF5C3F43)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD9DE)
val md_theme_dark_tertiary = Color(0xFFEBBF90)
val md_theme_dark_onTertiary = Color(0xFF452B08)
val md_theme_dark_tertiaryContainer = Color(0xFF5F411C)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDDBA)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191112)
val md_theme_dark_onBackground = Color(0xFFF0DEE0)
val md_theme_dark_surface = Color(0xFF191112)
val md_theme_dark_onSurface = Color(0xFFF0DEE0)
val md_theme_dark_surfaceVariant = Color(0xFF524345)
val md_theme_dark_onSurfaceVariant = Color(0xFFD6C2C3)
val md_theme_dark_outline = Color(0xFF9F8C8E)
val md_theme_dark_outlineVariant = Color(0xFF524345)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFF0DEE0)
val md_theme_dark_inverseOnSurface = Color(0xFF382E2F)
val md_theme_dark_inversePrimary = Color(0xFF8E4957)
val md_theme_dark_surfaceDim = Color(0xFF191112)
val md_theme_dark_surfaceBright = Color(0xFF413738)
val md_theme_dark_surfaceContainerLowest = Color(0xFF140C0D)
val md_theme_dark_surfaceContainerLow = Color(0xFF22191A)
val md_theme_dark_surfaceContainer = Color(0xFF261D1E)
val md_theme_dark_surfaceContainerHigh = Color(0xFF312829)
val md_theme_dark_surfaceContainerHighest = Color(0xFF3C3233)

// Legacy compatibility aliases
val Purple40 = md_theme_light_primary
val PurpleGrey40 = md_theme_light_secondary
val Purple80 = md_theme_dark_primary
val PurpleGrey80 = md_theme_dark_secondary
